# Generated by Django 4.1.5 on 2023-01-18 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_meta', '0002_alter_city_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('file_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sFilePath', to='project_meta.media', verbose_name='File Path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sUser', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'db_table': 'Resume',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerSkill',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('skill', models.ForeignKey(db_column='skill', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sSkill', to='project_meta.skill', verbose_name='Skill')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sUser', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Seeker Skill',
                'verbose_name_plural': 'Job Seeker Skills',
                'db_table': 'JobSeekerSkill',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerLanguageProficiency',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('written', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='written', max_length=255, verbose_name='Written')),
                ('spoken', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='spoken', max_length=255, verbose_name='Spoken')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sLanguage', to='project_meta.language', verbose_name='Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sUser', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Seeker Language Proficiency',
                'verbose_name_plural': 'Job Seeker Language Proficiencies',
                'db_table': 'JobSeekerLanguageProficiency',
            },
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True, verbose_name='End Date')),
                ('present', models.BooleanField(blank=True, db_column='present', default=True, null=True, verbose_name='Present')),
                ('organization', models.CharField(db_column='organization', max_length=255, verbose_name='Organization')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sUser', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employment Record',
                'verbose_name_plural': 'Employment Records',
                'db_table': 'EmploymentRecord',
            },
        ),
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True, verbose_name='End Date')),
                ('institute', models.CharField(db_column='institute', max_length=255, verbose_name='Institute')),
                ('organization', models.CharField(db_column='organization', max_length=255, verbose_name='Organization')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sUser', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Education Record',
                'verbose_name_plural': 'Education Records',
                'db_table': 'EducationRecord',
            },
        ),
    ]
