# Generated by Django 4.1.5 on 2023-01-18 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_meta', '0003_alter_city_active_alter_city_country_and_more'),
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationrecord',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='educationrecord',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='jobseekerlanguageproficiency',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='jobseekerlanguageproficiency',
            name='language',
            field=models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_language', to='project_meta.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='jobseekerlanguageproficiency',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='jobseekerskill',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='jobseekerskill',
            name='skill',
            field=models.ForeignKey(db_column='skill', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_skill', to='project_meta.skill', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='jobseekerskill',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_path',
            field=models.ForeignKey(db_column='file_path', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_file_path', to='project_meta.media', verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
