# Generated by Django 4.1.5 on 2023-01-31 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0004_remove_city_created_remove_city_modified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_seeker', '0006_educationrecord_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_path',
            field=models.OneToOneField(db_column='file_path', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_file_path', to='project_meta.media', verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
