# Generated by Django 4.1.5 on 2024-03-06 12:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('reason', models.TextField(blank=True, db_column='reason', null=True, verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Black List',
                'verbose_name_plural': 'Black Lists',
                'db_table': 'BlackList',
                'ordering': ['-created'],
            },
        ),
    ]
