# Generated by Django 4.1.5 on 2023-02-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'ordering': ['-created'], 'verbose_name': 'Black List', 'verbose_name_plural': 'Black Lists'},
        ),
    ]
