# Generated by Django 4.1.5 on 2023-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_blacklist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='reason',
            field=models.TextField(blank=True, db_column='reason', null=True, verbose_name='Reason'),
        ),
    ]
