# Generated by Django 4.1.5 on 2023-02-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_meta", "0003_country_educationlevel_language_skill_city"),
        ("users", "0002_user_active_usersession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.OneToOneField(
                blank=True,
                db_column="image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_image",
                to="project_meta.media",
                verbose_name="Image",
            ),
        ),
    ]
