# Generated by Django 4.1.5 on 2023-01-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_country_code_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                blank=True,
                db_column="mobile_number",
                max_length=13,
                null=True,
                verbose_name="Mobile Number",
            ),
        ),
    ]
