# Generated by Django 4.1.5 on 2023-01-12 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('job_seeker', 'Job Seeker'), ('employer', 'Employer'), ('vendor', 'Vendor')], db_column='profile_role', default='admin', max_length=250, null=True, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('agent', models.JSONField(null=True, verbose_name='Agent')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)sSession', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'UserSession',
            },
        ),
    ]
