# Generated by Django 4.1.5 on 2023-02-03 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                blank=True,
                db_column="country_code",
                max_length=250,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid country code", regex="^\\+[1-9]\\d{0,2}$"
                    )
                ],
                verbose_name="Country Code",
            ),
        ),
    ]
