# Generated by Django 4.1.5 on 2023-01-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_email_alter_user_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="created",),
        migrations.RemoveField(model_name="user", name="modified",),
        migrations.RemoveField(model_name="usersession", name="created",),
        migrations.RemoveField(model_name="usersession", name="modified",),
    ]
