# Generated by Django 4.1.5 on 2023-02-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['created'], 'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
    ]
