# Generated by Django 4.1.5 on 2023-02-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usersession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, db_column='otp', max_length=250, null=True, verbose_name='OTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, db_column='otp_created_at', null=True, verbose_name='OTP Created At'),
        ),
    ]
