# Generated by Django 4.1.5 on 2023-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersession_created_usersession_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('job_seeker', 'Job Seeker'), ('employer', 'Employer'), ('vendor', 'Vendor')], db_column='role', default='job_seeker', max_length=250, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
