# Generated by Django 4.1.5 on 2023-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_type',
            field=models.CharField(choices=[('app', 'App'), ('facebook', 'Facebook'), ('google', 'Google')], db_column='creation_type', default='app', max_length=250, verbose_name='Creation Type'),
        ),
    ]
