# Generated by Django 4.1.5 on 2023-03-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_creation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creation_type',
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('app', 'App'), ('facebook', 'Facebook'), ('google', 'Google')], db_column='source', default='app', max_length=250, verbose_name='Source'),
        ),
    ]
