# Generated by Django 4.1.5 on 2023-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=False, verbose_name='Is Verified'),
        ),
    ]
