# Generated by Django 4.1.5 on 2023-03-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(blank=True, db_column='is_verified', default=False, null=True, verbose_name='Is Verified'),
        ),
    ]
