# Generated by Django 4.1.5 on 2023-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_visitorlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'ordering': ['created_at'], 'verbose_name': 'Visitor Log', 'verbose_name_plural': 'Visitor Logs'},
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='created_at',
            field=models.DateField(blank=True, db_column='created_at', null=True, verbose_name='Created At'),
        ),
    ]
