# Generated by Django 4.1.5 on 2023-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_visitorlog_options_remove_visitorlog_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_email',
            field=models.BooleanField(db_column='get_email', default=True, verbose_name='Get Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='get_notification',
            field=models.BooleanField(db_column='get_notification', default=True, verbose_name='Get Notification'),
        ),
    ]
