# Generated by Django 4.1.5 on 2023-08-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_login_id',
            field=models.CharField(blank=True, db_column='social_login_id', max_length=250, null=True, verbose_name='Social Login Id'),
        ),
    ]
