# Generated by Django 4.1.5 on 2023-11-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_social_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='agent',
            field=models.JSONField(blank=True, db_column='agent', null=True, verbose_name='Agent'),
        ),
    ]
