# Generated by Django 4.1.5 on 2024-03-06 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAttachmentsItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Job Attachments Item',
                'verbose_name_plural': 'Job Attachments Items',
                'db_table': 'JobAttachmentsItem',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'JobCategory',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('job_id', models.CharField(blank=True, db_column='job_id', max_length=255, null=True, unique=True, verbose_name='Job Id')),
                ('budget_currency', models.CharField(blank=True, db_column='budget_currency', default='KES', max_length=5, null=True, verbose_name='Budget Currency')),
                ('budget_amount', models.DecimalField(blank=True, db_column='budget_amount', decimal_places=2, max_digits=19, null=True, verbose_name='Budget Amount')),
                ('budget_pay_period', models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('hourly', 'Hourly')], db_column='budget_pay_period', max_length=255, null=True, verbose_name='Budget Pay Period')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('address', models.TextField(db_column='address', verbose_name='Address')),
                ('is_full_time', models.BooleanField(blank=True, db_column='is_full_time', default=False, null=True, verbose_name='Is Full-time')),
                ('is_part_time', models.BooleanField(blank=True, db_column='is_part_time', default=False, null=True, verbose_name='Is Part-time')),
                ('has_contract', models.BooleanField(blank=True, db_column='has_contract', default=False, null=True, verbose_name='Has Contract')),
                ('contact_email', models.EmailField(blank=True, db_column='contact_email', max_length=254, null=True, verbose_name='Contact Email')),
                ('cc1', models.EmailField(blank=True, db_column='cc1', max_length=254, null=True, verbose_name='CC Email 1')),
                ('cc2', models.EmailField(blank=True, db_column='cc2', max_length=254, null=True, verbose_name='CC Email 2')),
                ('contact_whatsapp', models.CharField(blank=True, db_column='contact_whatsapp', max_length=15, null=True, verbose_name='Contact Whatsapp')),
                ('duration', models.BigIntegerField(blank=True, db_column='duration', null=True, verbose_name='Duration')),
                ('experience', models.BigIntegerField(blank=True, db_column='experience', null=True, verbose_name='Experience')),
                ('deadline', models.DateField(db_column='deadline', verbose_name='Deadline')),
                ('start_date', models.DateField(blank=True, db_column='start_date', null=True, verbose_name='Start Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hold', 'Hold'), ('deleted', 'Deleted'), ('expired', 'Expired')], db_column='status', max_length=25, verbose_name='Status')),
                ('post_by_admin', models.BooleanField(blank=True, db_column='post_by_admin', default=False, null=True, verbose_name='Post by Admin')),
                ('company', models.CharField(blank=True, db_column='company', max_length=255, null=True, verbose_name='Company Name')),
                ('apply_through_koor', models.BooleanField(blank=True, db_column='apply_through_koor', default=False, null=True, verbose_name='Apply Through Koor')),
                ('apply_through_email', models.BooleanField(blank=True, db_column='apply_through_email', default=False, null=True, verbose_name='Apply Through Email')),
                ('apply_through_website', models.BooleanField(blank=True, db_column='apply_through_website', default=False, null=True, verbose_name='Apply Through Website')),
                ('application_instruction', models.TextField(blank=True, db_column='application_instruction', null=True, verbose_name='Application Instruction')),
                ('website_link', models.CharField(blank=True, db_column='website_link', max_length=450, null=True, verbose_name='Website Link')),
            ],
            options={
                'verbose_name': 'Job Detail',
                'verbose_name_plural': 'Job Details',
                'db_table': 'JobDetails',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobFilters',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.TextField(db_column='title', verbose_name='Title')),
                ('is_full_time', models.BooleanField(blank=True, db_column='is_full_time', null=True, verbose_name='Is Full-time')),
                ('is_part_time', models.BooleanField(blank=True, db_column='is_part_time', null=True, verbose_name='Is Part-time')),
                ('is_notification', models.BooleanField(blank=True, db_column='is_notification', null=True, verbose_name='Is Notification')),
                ('has_contract', models.BooleanField(blank=True, db_column='has_contract', null=True, verbose_name='Has Contract')),
                ('duration', models.BigIntegerField(blank=True, db_column='duration', null=True, verbose_name='Duration')),
                ('salary_min', models.CharField(blank=True, db_column='salary_min', max_length=250, null=True, verbose_name='Salary Min')),
                ('salary_max', models.CharField(blank=True, db_column='salary_max', max_length=250, null=True, verbose_name='Salary Max')),
            ],
            options={
                'verbose_name': 'Job Filter',
                'verbose_name_plural': 'Job Filters',
                'db_table': 'JobFilters',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobShare',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('whatsapp', models.BigIntegerField(db_column='whatsapp', default=0, verbose_name='Whats App')),
                ('telegram', models.BigIntegerField(db_column='telegram', default=0, verbose_name='Telegram')),
                ('facebook', models.BigIntegerField(db_column='facebook', default=0, verbose_name='Facebook')),
                ('linked_in', models.BigIntegerField(db_column='linked_in', default=0, verbose_name='Linked In')),
                ('mail', models.BigIntegerField(db_column='mail', default=0, verbose_name='Mail')),
                ('direct_link', models.BigIntegerField(db_column='direct_link', default=0, verbose_name='Direct Link')),
            ],
            options={
                'verbose_name': 'Job Share',
                'verbose_name_plural': 'Job Shares',
                'db_table': 'JobShare',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobsLanguageProficiency',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('written', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='written', default='fluent', max_length=255, verbose_name='Written')),
                ('spoken', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='spoken', default='fluent', max_length=255, verbose_name='Spoken')),
            ],
            options={
                'verbose_name': 'Jobs Language Proficiency',
                'verbose_name_plural': 'Jobs Language Proficiencies',
                'db_table': 'JobsLanguageProficiency',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobSubCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_categories', to='jobs.jobcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Job Sub Category',
                'verbose_name_plural': 'Job Sub Categories',
                'db_table': 'JobSubCategory',
                'ordering': ['title'],
            },
        ),
    ]
