# Generated by Django 4.1.5 on 2024-05-28 11:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, max_length=255, null=True, populate_from='title', unique_with=('created__month',)),
        ),
    ]
