# Generated by Django 4.1.5 on 2023-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobdetails_job_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='working_days',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], db_column='working_days', default=1, max_length=25, verbose_name='Working Days'),
            preserve_default=False,
        ),
    ]
