# Generated by Django 4.1.5 on 2023-02-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobdetails_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobattachmentsitem',
            name='job',
            field=models.ForeignKey(db_column='job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_job', to='jobs.jobdetails', verbose_name='Job'),
        ),
    ]
