# Generated by Django 4.1.5 on 2023-02-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobattachmentsitem_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='deadline',
            field=models.DateField(db_column='deadline', default='2023-11-03', verbose_name='Deadline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='budget_amount',
            field=models.DecimalField(blank=True, db_column='budget_amount', decimal_places=2, max_digits=19, null=True, verbose_name='Budget Amount'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='budget_currency',
            field=models.CharField(blank=True, db_column='budget_currency', default='KES', max_length=5, null=True, verbose_name='Budget Currency'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='budget_pay_period',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('hourly', 'Hourly')], db_column='budget_pay_period', max_length=255, null=True, verbose_name='Budget Pay Period'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hold', 'Hold'), ('deleted', 'Deleted'), ('expired', 'Expired')], db_column='status', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='working_days',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], db_column='working_days', max_length=25, verbose_name='Working Days'),
        ),
    ]
