# Generated by Django 4.1.5 on 2023-02-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobdetails_deadline_alter_jobdetails_budget_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobattachmentsitem',
            options={'ordering': ['-created'], 'verbose_name': 'Job Attachments Item', 'verbose_name_plural': 'Job Attachments Items'},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['title'], 'verbose_name': 'Job Category', 'verbose_name_plural': 'Job Categories'},
        ),
        migrations.AlterModelOptions(
            name='jobdetails',
            options={'ordering': ['-created'], 'verbose_name': 'Job Detail', 'verbose_name_plural': 'Job Details'},
        ),
    ]
