# Generated by Django 4.1.5 on 2023-02-24 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_meta', '0005_alter_city_options_alter_country_options_and_more'),
        ('jobs', '0008_alter_jobattachmentsitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='language',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='start_date',
            field=models.DateField(db_column='start_date', default='2023-02-01', verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobsLanguageProficiency',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('written', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='written', max_length=255, verbose_name='Written')),
                ('spoken', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='spoken', max_length=255, verbose_name='Spoken')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('job', models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_job', to='jobs.jobdetails', verbose_name='Job')),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_language', to='project_meta.language', verbose_name='Language')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Jobs Language Proficiency',
                'verbose_name_plural': 'Jobs Language Proficiencies',
                'db_table': 'JobsLanguageProficiency',
                'ordering': ['-created'],
            },
        ),
    ]
