# Generated by Django 4.1.5 on 2023-03-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_jobdetails_language_jobdetails_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='job_id',
            field=models.CharField(db_column='job_id', default='111-2222', max_length=255, verbose_name='Job Id'),
            preserve_default=False,
        ),
    ]
