# Generated by Django 4.1.5 on 2023-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobdetails_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_id',
            field=models.CharField(db_column='job_id', max_length=255, unique=True, verbose_name='Job Id'),
        ),
    ]
