# Generated by Django 4.1.5 on 2023-03-17 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0005_alter_city_options_alter_country_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0012_alter_jobdetails_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFilters',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.TextField(blank=True, db_column='title', null=True, verbose_name='Title')),
                ('is_full_time', models.BooleanField(blank=True, db_column='is_full_time', default=False, null=True, verbose_name='Is Full-time')),
                ('is_part_time', models.BooleanField(blank=True, db_column='is_part_time', default=False, null=True, verbose_name='Is Part-time')),
                ('has_contract', models.BooleanField(blank=True, db_column='has_contract', default=False, null=True, verbose_name='Has Contract')),
                ('working_days', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], db_column='working_days', max_length=25, verbose_name='Working Days')),
                ('city', models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City')),
                ('country', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('job_category', models.ManyToManyField(db_column='job_category', related_name='%(app_label)s_%(class)s_job_category', to='jobs.jobcategory', verbose_name='Job Category')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Filter',
                'verbose_name_plural': 'Job Filters',
                'db_table': 'JobFilters',
                'ordering': ['-created'],
            },
        ),
    ]
