# Generated by Django 4.1.5 on 2023-03-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobfilters'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfilters',
            name='is_notification',
            field=models.BooleanField(blank=True, db_column='is_notification', default=False, null=True, verbose_name='Is Notification'),
        ),
    ]
