# Generated by Django 4.1.5 on 2023-03-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0005_alter_city_options_alter_country_options_and_more'),
        ('jobs', '0014_jobfilters_is_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfilters',
            name='city',
            field=models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='jobfilters',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='jobfilters',
            name='job_category',
            field=models.ManyToManyField(blank=True, db_column='job_category', null=True, related_name='%(app_label)s_%(class)s_job_category', to='jobs.jobcategory', verbose_name='Job Category'),
        ),
        migrations.AlterField(
            model_name='jobfilters',
            name='title',
            field=models.TextField(db_column='title', default='test', verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobfilters',
            name='working_days',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], db_column='working_days', max_length=25, null=True, verbose_name='Working Days'),
        ),
    ]
