# Generated by Django 4.1.5 on 2023-03-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobfilters_city_alter_jobfilters_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfilters',
            name='has_contract',
            field=models.BooleanField(blank=True, db_column='has_contract', null=True, verbose_name='Has Contract'),
        ),
        migrations.AlterField(
            model_name='jobfilters',
            name='is_full_time',
            field=models.BooleanField(blank=True, db_column='is_full_time', null=True, verbose_name='Is Full-time'),
        ),
        migrations.AlterField(
            model_name='jobfilters',
            name='is_notification',
            field=models.BooleanField(blank=True, db_column='is_notification', null=True, verbose_name='Is Notification'),
        ),
        migrations.AlterField(
            model_name='jobfilters',
            name='is_part_time',
            field=models.BooleanField(blank=True, db_column='is_part_time', null=True, verbose_name='Is Part-time'),
        ),
    ]
