# Generated by Django 4.1.5 on 2023-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0008_sector'),
        ('jobs', '0016_alter_jobfilters_has_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='skill',
            field=models.ManyToManyField(blank=True, db_column='skill', null=True, related_name='%(app_label)s_%(class)s_skill', to='project_meta.skill', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='start_date',
            field=models.DateField(blank=True, db_column='start_date', null=True, verbose_name='Start Date'),
        ),
    ]
