# Generated by Django 4.1.5 on 2023-04-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_jobdetails_skill_alter_jobdetails_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='jobfilters',
            name='working_days',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='duration',
            field=models.BigIntegerField(blank=True, db_column='duration', null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='experience',
            field=models.BigIntegerField(blank=True, db_column='experience', null=True, verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='jobfilters',
            name='duration',
            field=models.BigIntegerField(blank=True, db_column='duration', null=True, verbose_name='Duration'),
        ),
    ]
