# Generated by Django 4.1.5 on 2023-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_jobdetails_job_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfilters',
            name='job_sub_category',
            field=models.ManyToManyField(blank=True, db_column='job_sub_category', null=True, related_name='%(app_label)s_%(class)s_job_sub_category', to='jobs.jobsubcategory', verbose_name='Job Sub Category'),
        ),
    ]
