# Generated by Django 4.1.5 on 2023-04-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_jobshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshare',
            name='direct_link',
            field=models.BigIntegerField(db_column='direct_link', default=0, verbose_name='Direct Link'),
        ),
        migrations.AddField(
            model_name='jobshare',
            name='linked_in',
            field=models.BigIntegerField(db_column='linked_in', default=0, verbose_name='Linked In'),
        ),
    ]
