# Generated by Django 4.1.5 on 2023-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_jobshare_direct_link_jobshare_linked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='cc1',
            field=models.EmailField(blank=True, db_column='cc1', max_length=254, null=True, verbose_name='CC Email 1'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='cc2',
            field=models.EmailField(blank=True, db_column='cc2', max_length=254, null=True, verbose_name='CC Email 2'),
        ),
    ]
