# Generated by Django 4.1.5 on 2023-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_remove_jobdetails_contact_phone_jobdetails_cc1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobslanguageproficiency',
            name='spoken',
            field=models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='spoken', default='fluent', max_length=255, verbose_name='Spoken'),
        ),
        migrations.AlterField(
            model_name='jobslanguageproficiency',
            name='written',
            field=models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='written', default='fluent', max_length=255, verbose_name='Written'),
        ),
    ]
