# Generated by Django 4.1.5 on 2023-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_jobdetails_company_jobdetails_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='application_instruction',
            field=models.TextField(blank=True, db_column='application_instruction', null=True, verbose_name='Application Instruction'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='apply_through_email',
            field=models.BooleanField(blank=True, db_column='apply_through_email', default=False, null=True, verbose_name='Apply Through Email'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='apply_through_koor',
            field=models.BooleanField(blank=True, db_column='apply_through_koor', default=False, null=True, verbose_name='Apply Through Koor'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='apply_through_website',
            field=models.BooleanField(blank=True, db_column='apply_through_website', default=False, null=True, verbose_name='Apply Through Website'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='website_link',
            field=models.CharField(blank=True, db_column='website_link', max_length=450, null=True, verbose_name='Website Link'),
        ),
    ]
