# Generated by Django 4.1.5 on 2023-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_jobdetails_application_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobsubcategory',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
    ]
