# Generated by Django 4.1.5 on 2024-03-06 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seekers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('notification_type', models.CharField(choices=[('applied', 'Applied'), ('applied_tender', 'Applied Tender'), ('password_update', 'Password Updated'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('planned_interviews', 'Planned Interviews'), ('message', 'Message'), ('advance_filter', 'Advance Filter'), ('expired_save_job', 'Expired Save Job'), ('message', 'Message')], db_column='nitification_type', max_length=25, verbose_name='Notification Type')),
                ('message', models.CharField(blank=True, db_column='message', max_length=255, null=True, verbose_name='Message')),
                ('message_id', models.CharField(blank=True, db_column='message_id', max_length=255, null=True, verbose_name='Message Id')),
                ('message_sender', models.CharField(blank=True, db_column='message_sender', max_length=255, null=True, verbose_name='Message Sender')),
                ('conversation_id', models.CharField(blank=True, db_column='conversation_id', max_length=255, null=True, verbose_name='Conversation Id')),
                ('seen', models.BooleanField(blank=True, db_column='seen', default=False, null=True, verbose_name='Seen')),
                ('application', models.ForeignKey(blank=True, db_column='application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_applications', to='job_seekers.appliedjob', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notification',
                'ordering': ['-created'],
            },
        ),
    ]
