# Generated by Django 4.1.5 on 2023-03-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0014_alter_appliedjob_options_and_more'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='job',
        ),
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, db_column='application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_applications', to='job_seekers.appliedjob', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(blank=True, db_column='seen', default=False, null=True, verbose_name='Seen'),
        ),
    ]
