# Generated by Django 4.1.5 on 2023-03-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('applied', 'Applied'), ('password update', 'Password Updated'), ('shortlisted', 'Shortlisted'), ('message', 'Message'), ('advance filter', 'Advance Filter')], db_column='nitification_type', default='', max_length=25, verbose_name='Notification Type'),
            preserve_default=False,
        ),
    ]
