# Generated by Django 4.1.5 on 2023-03-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_options_remove_notification_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('applied', 'Applied'), ('password_update', 'Password Updated'), ('shortlisted', 'Shortlisted'), ('message', 'Message'), ('advance_filter', 'Advance Filter')], db_column='nitification_type', max_length=25, verbose_name='Notification Type'),
        ),
    ]
