# Generated by Django 4.1.5 on 2023-03-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_jobfilters_has_contract_and_more'),
        ('notification', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, db_column='job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_jobs', to='jobs.jobdetails', verbose_name='Job'),
        ),
    ]
