# Generated by Django 4.1.5 on 2023-05-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_appliedtender_appliedtenderattachmentsitem'),
        ('notification', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tender_application',
            field=models.ForeignKey(blank=True, db_column='tender_application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tender_application', to='vendors.appliedtender', verbose_name='Tender Application'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('applied', 'Applied'), ('applied_tender', 'Applied Tender'), ('password_update', 'Password Updated'), ('shortlisted', 'Shortlisted'), ('planned_interviews', 'Planned Interviews'), ('message', 'Message'), ('advance_filter', 'Advance Filter'), ('expired_save_job', 'Expired Save Job')], db_column='nitification_type', max_length=25, verbose_name='Notification Type'),
        ),
    ]
