# Generated by Django 4.1.5 on 2023-09-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation_id',
            field=models.CharField(blank=True, db_column='conversation_id', max_length=255, null=True, verbose_name='Conversation Id'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_sender',
            field=models.CharField(blank=True, db_column='message_sender', max_length=255, null=True, verbose_name='Message Sender'),
        ),
    ]
