# Generated by Django 4.1.5 on 2023-09-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0017_tenderdetails_company_tenderdetails_company_logo_and_more'),
        ('notification', '0011_notification_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tender',
            field=models.ForeignKey(blank=True, db_column='tender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenders', to='tenders.tenderdetails', verbose_name='Tender'),
        ),
    ]
