# Generated by Django 4.1.5 on 2023-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_notification_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_id',
            field=models.CharField(blank=True, db_column='message_id', max_length=255, null=True, verbose_name='Message Id'),
        ),
    ]
