# Generated by Django 4.1.5 on 2024-03-06 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderAttachmentsItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Tender Attachments Item',
                'verbose_name_plural': 'Tender Attachments Items',
                'db_table': 'TenderAttachmentsItem',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TenderCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tender Category',
                'verbose_name_plural': 'Tender Categories',
                'db_table': 'TenderCategory',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TenderDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('tender_id', models.CharField(blank=True, db_column='tender_id', max_length=255, null=True, unique=True, verbose_name='Tender Id')),
                ('budget_currency', models.CharField(blank=True, db_column='budget_currency', default='KES', max_length=5, null=True, verbose_name='Budget Currency')),
                ('budget_amount', models.DecimalField(blank=True, db_column='budget_amount', decimal_places=2, max_digits=19, null=True, verbose_name='Budget Amount')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, db_column='address', null=True, verbose_name='Address')),
                ('deadline', models.DateField(db_column='deadline', verbose_name='Deadline')),
                ('start_date', models.DateField(blank=True, db_column='start_date', null=True, verbose_name='Start Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hold', 'Hold'), ('deleted', 'Deleted'), ('expired', 'Expired')], db_column='status', max_length=25, verbose_name='Status')),
                ('post_by_admin', models.BooleanField(blank=True, db_column='post_by_admin', default=False, null=True, verbose_name='Post by Admin')),
                ('company', models.CharField(blank=True, db_column='company', max_length=255, null=True, verbose_name='Company Name')),
                ('contact_email', models.EmailField(blank=True, db_column='contact_email', max_length=254, null=True, verbose_name='Contact Email')),
                ('cc1', models.EmailField(blank=True, db_column='cc1', max_length=254, null=True, verbose_name='CC Email 1')),
                ('cc2', models.EmailField(blank=True, db_column='cc2', max_length=254, null=True, verbose_name='CC Email 2')),
                ('contact_whatsapp', models.CharField(blank=True, db_column='contact_whatsapp', max_length=15, null=True, verbose_name='Contact Whatsapp')),
                ('apply_through_koor', models.BooleanField(blank=True, db_column='apply_through_koor', default=False, null=True, verbose_name='Apply Through Koor')),
                ('apply_through_email', models.BooleanField(blank=True, db_column='apply_through_email', default=False, null=True, verbose_name='Apply Through Email')),
                ('apply_through_website', models.BooleanField(blank=True, db_column='apply_through_website', default=False, null=True, verbose_name='Apply Through Website')),
                ('application_instruction', models.TextField(blank=True, db_column='application_instruction', null=True, verbose_name='Application Instruction')),
                ('website_link', models.CharField(blank=True, db_column='website_link', max_length=450, null=True, verbose_name='Website Link')),
            ],
            options={
                'verbose_name': 'Tender Detail',
                'verbose_name_plural': 'Tender Details',
                'db_table': 'TenderDetails',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TenderFilter',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.TextField(db_column='title', verbose_name='Title')),
                ('deadline', models.DateField(blank=True, db_column='deadline', null=True, verbose_name='Deadline')),
                ('budget_min', models.DecimalField(blank=True, db_column='budget_min', decimal_places=2, max_digits=19, null=True, verbose_name='Budget Minimum')),
                ('budget_max', models.DecimalField(blank=True, db_column='budget_max', decimal_places=2, max_digits=19, null=True, verbose_name='Budget Maximum')),
                ('is_notification', models.BooleanField(blank=True, db_column='is_notification', null=True, verbose_name='Is Notification')),
                ('city', models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City')),
                ('country', models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Tender Filter',
                'verbose_name_plural': 'Tender Filters',
                'db_table': 'TenderFilter',
                'ordering': ['-created'],
            },
        ),
    ]
