# Generated by Django 4.1.5 on 2023-04-05 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_meta', '0007_remove_jobseekercategory_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, db_column='slug', null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Tender Category',
                'verbose_name_plural': 'Tender Categories',
                'db_table': 'TenderCategory',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TenderDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('tender_id', models.CharField(blank=True, db_column='tender_id', max_length=255, null=True, unique=True, verbose_name='Tender Id')),
                ('budget_currency', models.CharField(blank=True, db_column='budget_currency', default='KES', max_length=5, null=True, verbose_name='Budget Currency')),
                ('budget_amount', models.DecimalField(blank=True, db_column='budget_amount', decimal_places=2, max_digits=19, null=True, verbose_name='Budget Amount')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('tender_type', models.CharField(choices=[('government', 'Government'), ('ngo', 'NGO'), ('business', 'Business')], db_column='tender_type', max_length=25, verbose_name='Tender Type')),
                ('sector', models.CharField(choices=[('ngo', 'NGO'), ('private', 'Private'), ('public', 'Public')], db_column='sector', max_length=25, verbose_name='Sector')),
                ('city', models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City')),
                ('country', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('tag', models.ManyToManyField(db_column='tag', related_name='%(app_label)s_%(class)s_tag', to='project_meta.tag', verbose_name='Tag')),
                ('tender_category', models.ManyToManyField(db_column='tender_category', related_name='%(app_label)s_%(class)s_tender_category', to='tenders.tendercategory', verbose_name='Tender Category')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tender Detail',
                'verbose_name_plural': 'Tender Details',
                'db_table': 'TenderDetails',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TenderAttachmentsItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('attachment', models.OneToOneField(db_column='attachment', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_attachment', to='project_meta.media', verbose_name='Attachment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('tender', models.ForeignKey(db_column='tender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenders', to='tenders.tenderdetails', verbose_name='Tender')),
            ],
            options={
                'verbose_name': 'Tender Attachments Item',
                'verbose_name_plural': 'Tender Attachments Items',
                'db_table': 'TenderAttachmentsItem',
                'ordering': ['-created'],
            },
        ),
    ]
