# Generated by Django 4.1.5 on 2024-03-06 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_meta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderfilter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='tenderfilter',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='tenderfilter',
            name='opportunity_type',
            field=models.ManyToManyField(blank=True, db_column='opportunity_type', null=True, related_name='%(app_label)s_%(class)s_opportunity_types', to='project_meta.opportunitytype', verbose_name='Opportunity Type'),
        ),
        migrations.AddField(
            model_name='tenderfilter',
            name='sector',
            field=models.ManyToManyField(blank=True, db_column='sector', null=True, related_name='%(app_label)s_%(class)s_sector', to='project_meta.choice', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='tenderfilter',
            name='tag',
            field=models.ManyToManyField(blank=True, db_column='tag', null=True, related_name='%(app_label)s_%(class)s_tags', to='project_meta.tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='tenderfilter',
            name='tender_category',
            field=models.ManyToManyField(blank=True, db_column='tender_category', null=True, related_name='%(app_label)s_%(class)s_tender_category', to='tenders.tendercategory', verbose_name='Tender Category'),
        ),
        migrations.AddField(
            model_name='tenderfilter',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='city',
            field=models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='company_logo',
            field=models.OneToOneField(blank=True, db_column='company_logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_company_logo', to='project_meta.media', verbose_name='Company Logo'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='country',
            field=models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='sector',
            field=models.ManyToManyField(blank=True, db_column='sector', null=True, related_name='%(app_label)s_%(class)s_sectors', to='project_meta.choice', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='tag',
            field=models.ManyToManyField(db_column='tag', related_name='%(app_label)s_%(class)s_tag', to='project_meta.tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='tender_category',
            field=models.ManyToManyField(db_column='tender_category', related_name='%(app_label)s_%(class)s_tender_category', to='tenders.tendercategory', verbose_name='Tender Category'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='tender_type',
            field=models.ManyToManyField(blank=True, db_column='tender_type', null=True, related_name='%(app_label)s_%(class)s_tender_type', to='project_meta.opportunitytype', verbose_name='Tender Type'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='tendercategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='tendercategory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='tenderattachmentsitem',
            name='attachment',
            field=models.OneToOneField(db_column='attachment', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_attachment', to='project_meta.media', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='tenderattachmentsitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='tenderattachmentsitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='tenderattachmentsitem',
            name='tender',
            field=models.ForeignKey(db_column='tender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenders', to='tenders.tenderdetails', verbose_name='Tender'),
        ),
    ]
