# Generated by Django 4.1.5 on 2023-04-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdetails',
            name='deadline',
            field=models.DateField(db_column='deadline', default='2023-07-05', verbose_name='Deadline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='start_date',
            field=models.DateField(db_column='start_date', default='2023-04-05', verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hold', 'Hold'), ('deleted', 'Deleted'), ('expired', 'Expired')], db_column='status', default='active', max_length=25, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
