# Generated by Django 4.1.5 on 2023-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tenderfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderfilter',
            name='budget',
        ),
        migrations.AddField(
            model_name='tenderfilter',
            name='budget_max',
            field=models.DecimalField(blank=True, db_column='budget_max', decimal_places=2, max_digits=19, null=True, verbose_name='Budget Maximum'),
        ),
        migrations.AddField(
            model_name='tenderfilter',
            name='budget_min',
            field=models.DecimalField(blank=True, db_column='budget_min', decimal_places=2, max_digits=19, null=True, verbose_name='Budget Minimum'),
        ),
    ]
