# Generated by Django 4.1.5 on 2023-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_remove_tenderdetails_sector_tenderdetails_sector'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='tenderdetails',
        #     name='sector',
        # ),
        # migrations.AddField(
        #     model_name='tenderdetails',
        #     name='sector',
        #     field=models.CharField(choices=[('ngo', 'NGO'), ('private', 'Private'), ('public', 'Public')], db_column='sector', default='ngo', max_length=25, verbose_name='Sector'),
        #     preserve_default=False,
        # ),
    ]
