# Generated by Django 4.1.5 on 2023-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_remove_tenderdetails_sector_tenderdetails_sector'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='tenderdetails',
        #     name='sector',
        #     field=models.CharField(choices=[('government', 'Government'), ('ngo', 'NGO'), ('business', 'Business'), ('private', 'Private'), ('public', 'Public')], db_column='sector', max_length=25, verbose_name='Sector'),
        # ),
        # migrations.AlterField(
        #     model_name='tenderfilter',
        #     name='sector',
        #     field=models.CharField(blank=True, choices=[('government', 'Government'), ('ngo', 'NGO'), ('business', 'Business'), ('private', 'Private'), ('public', 'Public')], db_column='sector', max_length=105, null=True, verbose_name='Sector'),
        # ),
    ]
