# Generated by Django 4.1.5 on 2023-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0015_choice'),
        ('tenders', '0007_alter_tenderdetails_sector_alter_tenderfilter_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderdetails',
            name='sector',
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='sector',
            field=models.ManyToManyField(db_column='sector', related_name='%(app_label)s_%(class)s_sectors', to='project_meta.choice', verbose_name='Sector'),
        ),
    ]
