# Generated by Django 4.1.5 on 2023-05-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0015_choice'),
        ('tenders', '0008_remove_tenderdetails_sector_tenderdetails_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderfilter',
            name='sector',
        ),
        migrations.AddField(
            model_name='tenderfilter',
            name='sector',
            field=models.ManyToManyField(db_column='sector', related_name='%(app_label)s_%(class)s_sector', to='project_meta.choice', verbose_name='Sector'),
        ),
    ]
