# Generated by Django 4.1.5 on 2023-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_remove_tenderdetails_tender_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdetails',
            name='start_date',
            field=models.DateField(blank=True, db_column='start_date', null=True, verbose_name='Start Date'),
        ),
    ]
