# Generated by Django 4.1.5 on 2023-05-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0016_rename_sector_opportunitytype_and_more'),
        ('tenders', '0010_alter_tenderdetails_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderfilter',
            name='opportunity_type',
            field=models.ManyToManyField(blank=True, db_column='opportunity_type', null=True, related_name='%(app_label)s_%(class)s_opportunity_types', to='project_meta.opportunitytype', verbose_name='Opportunity Type'),
        ),
        migrations.AlterField(
            model_name='tenderfilter',
            name='sector',
            field=models.ManyToManyField(blank=True, db_column='sector', null=True, related_name='%(app_label)s_%(class)s_sector', to='project_meta.choice', verbose_name='Sector'),
        ),
    ]
