# Generated by Django 4.1.5 on 2023-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0014_tenderdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdetails',
            name='sector',
            field=models.ManyToManyField(db_column='sector', related_name='%(app_label)s_%(class)s_sectors', to='project_meta.choice', verbose_name='Sector'),
        ),
    ]
