# Generated by Django 4.1.5 on 2023-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0015_sectors_tenderdetails_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdetails',
            name='post_by_admin',
            field=models.BooleanField(blank=True, db_column='post_by_admin', default=False, null=True, verbose_name='Post by Admin'),
        ),
    ]
