# Generated by Django 4.1.5 on 2023-08-03 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_meta', '0017_alter_media_file_path'),
        ('tenders', '0016_tenderdetails_post_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdetails',
            name='company',
            field=models.CharField(blank=True, db_column='company', max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='company_logo',
            field=models.OneToOneField(blank=True, db_column='company_logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_company_logo', to='project_meta.media', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='tenderdetails',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
