# Generated by Django 4.1.5 on 2023-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0017_tenderdetails_company_tenderdetails_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendercategory',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
    ]
