# Generated by Django 4.1.5 on 2023-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0018_alter_tendercategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendercategory',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True),
        ),
    ]
