# Generated by Django 4.1.5 on 2023-11-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0019_alter_choice_slug_alter_city_slug_alter_country_slug_and_more'),
        ('tenders', '0020_tenderdetails_application_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdetails',
            name='sector',
            field=models.ManyToManyField(blank=True, db_column='sector', null=True, related_name='%(app_label)s_%(class)s_sectors', to='project_meta.choice', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='tenderdetails',
            name='tender_type',
            field=models.ManyToManyField(blank=True, db_column='tender_type', null=True, related_name='%(app_label)s_%(class)s_tender_type', to='project_meta.opportunitytype', verbose_name='Tender Type'),
        ),
    ]
