# Generated by Django 4.1.5 on 2023-01-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0002_alter_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='language',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='active',
            field=models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active'),
        ),
    ]
