# Generated by Django 4.1.5 on 2023-02-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0003_country_educationlevel_language_skill_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=250, null=True, verbose_name='Title'),
        ),
    ]
