# Generated by Django 4.1.5 on 2023-01-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_meta", "0003_alter_city_active_alter_city_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="city", name="created",),
        migrations.RemoveField(model_name="city", name="modified",),
        migrations.RemoveField(model_name="country", name="created",),
        migrations.RemoveField(model_name="country", name="modified",),
        migrations.RemoveField(model_name="educationlevel", name="created",),
        migrations.RemoveField(model_name="educationlevel", name="modified",),
        migrations.RemoveField(model_name="language", name="created",),
        migrations.RemoveField(model_name="language", name="modified",),
        migrations.RemoveField(model_name="media", name="created",),
        migrations.RemoveField(model_name="media", name="modified",),
        migrations.RemoveField(model_name="skill", name="created",),
        migrations.RemoveField(model_name="skill", name="modified",),
        migrations.RemoveField(model_name="tag", name="created",),
        migrations.RemoveField(model_name="tag", name="modified",),
    ]
