# Generated by Django 4.1.5 on 2023-02-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0004_media_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['title'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['title'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['title'], 'verbose_name': 'Education Level', 'verbose_name_plural': 'Education Levels'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['title'], 'verbose_name': 'Language', 'verbose_name_plural': 'Langauges'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['title'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
