# Generated by Django 4.1.5 on 2023-03-31 15:18

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0005_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerCategory',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, db_column='slug', null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_categories', to='project_meta.jobseekercategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'JobSeekerCategory',
                'verbose_name_plural': 'Job Seeker Categories',
                'db_table': 'JobSeekerCategory',
                'ordering': ['title'],
            },
        ),
    ]
