# Generated by Django 4.1.5 on 2023-03-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0006_jobseekercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekercategory',
            name='active',
        ),
        migrations.RemoveField(
            model_name='jobseekercategory',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='jobseekercategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='jobseekercategory',
            name='title',
            field=models.TextField(db_column='title', verbose_name='Title'),
        ),
    ]
