# Generated by Django 4.1.5 on 2023-04-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0008_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=150, verbose_name='Title')),
                ('iso3', models.CharField(db_column='iso3', max_length=10, verbose_name='ISO Code 3')),
                ('iso2', models.CharField(db_column='iso2', max_length=10, verbose_name='ISO Code 2')),
                ('numeric_code', models.BigIntegerField(blank=True, db_column='numeric_code', null=True, verbose_name='Numeric Code')),
                ('phone_code', models.CharField(db_column='phone_code', max_length=10, verbose_name='Phone Code')),
                ('capital', models.CharField(db_column='capital', max_length=100, verbose_name='Capital')),
                ('currency', models.CharField(db_column='currency', max_length=20, verbose_name='Currency')),
                ('currency_name', models.CharField(db_column='currency_name', max_length=80, verbose_name='Currency Name')),
                ('currency_symbol', models.TextField(blank=True, db_column='currency_symbol', null=True, verbose_name='Currency Symbol')),
                ('tld', models.CharField(db_column='tld', max_length=10, verbose_name='tld')),
                ('native', models.CharField(db_column='native', max_length=200, verbose_name='Native')),
                ('region', models.CharField(db_column='region', max_length=150, verbose_name='Region')),
                ('subregion', models.CharField(db_column='subregion', max_length=50, verbose_name='Subregion')),
                ('timezones', models.TextField(blank=True, db_column='timezones', null=True, verbose_name='Timezones')),
                ('latitude', models.CharField(db_column='latitude', max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(db_column='longitude', max_length=100, verbose_name='Longitude')),
                ('emoji', models.TextField(blank=True, db_column='emoji', null=True, verbose_name='Emoji ')),
                ('emojiU', models.TextField(blank=True, db_column='emojiU', null=True, verbose_name='emoji U')),
            ],
            options={
                'verbose_name': 'All Country',
                'verbose_name_plural': 'All Countries',
                'db_table': 'AllCountry',
                'ordering': ['title'],
            },
        ),
    ]
