# Generated by Django 4.1.5 on 2023-04-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0010_alter_allcountry_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=150, verbose_name='Title')),
                ('country', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_country', to='project_meta.allcountry', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'All City',
                'verbose_name_plural': 'All Cities',
                'db_table': 'AllCity',
                'ordering': ['title'],
            },
        ),
    ]
