# Generated by Django 4.1.5 on 2023-05-03 15:34

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0012_remove_allcountry_capital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekercategory',
            options={'ordering': ['-created'], 'verbose_name': 'JobSeekerCategory', 'verbose_name_plural': 'Job Seeker Categories'},
        ),
        migrations.AddField(
            model_name='jobseekercategory',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='jobseekercategory',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
