# Generated by Django 4.1.5 on 2023-05-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0013_alter_jobseekercategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeekerCategory',
        ),
    ]
