# Generated by Django 4.1.5 on 2023-05-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0015_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sector',
            new_name='OpportunityType',
        ),
        migrations.AlterModelOptions(
            name='opportunitytype',
            options={'ordering': ['title'], 'verbose_name': 'Opportunity Type', 'verbose_name_plural': 'Opportunity Types'},
        ),
        migrations.AlterModelTable(
            name='opportunitytype',
            table='OpportunityType',
        ),
    ]
