# Generated by Django 4.1.5 on 2023-06-22 12:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0016_rename_sector_opportunitytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_path',
            field=models.FileField(db_column='file_path', upload_to=core.models.upload_directory_path, verbose_name='File Path'),
        ),
    ]
