# Generated by Django 4.1.5 on 2023-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0017_alter_media_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='opportunitytype',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=255, null=True, unique=True),
        ),
    ]
