# Generated by Django 4.1.5 on 2023-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0018_alter_choice_slug_alter_city_slug_alter_country_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='opportunitytype',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=455, null=True, unique=True),
        ),
    ]
