# Generated by Django 4.1.5 on 2023-05-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0016_rename_sector_opportunitytype_and_more'),
        ('chat', '0002_remove_chatmessage_is_editable_chatmessage_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.OneToOneField(blank=True, db_column='attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_attachment', to='project_meta.media', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='conversationuser',
            name='conversation',
            field=models.OneToOneField(db_column='conversation', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_conversations', to='chat.conversation', verbose_name='Conversation'),
        ),
    ]
