# Generated by Django 4.1.5 on 2023-05-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_chat_user_delete_conversationuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-modified'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
    ]
