# Generated by Django 4.1.5 on 2023-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content_type',
            field=models.CharField(db_column='content_type', default='text', editable=False, max_length=255, verbose_name='Content Type'),
        ),
    ]
