# Generated by Django 4.1.5 on 2023-02-23 15:14

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSetting',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('smtp_host', models.CharField(db_column='smtp_host', max_length=255, verbose_name='SMTP Host')),
                ('smtp_user', models.CharField(db_column='smtp_user', max_length=255, verbose_name='SMTP User')),
                ('smtp_port', models.CharField(db_column='smtp_port', max_length=255, verbose_name='SMTP Port')),
                ('smtp_password', models.CharField(db_column='smtp_password', max_length=255, verbose_name='SMTP Password')),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
                'db_table': 'SMTPSetting',
            },
        ),
    ]
