# Generated by Django 4.1.5 on 2023-03-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_content_slug_content_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlaceApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('api_key', models.CharField(db_column='api_key', max_length=255, verbose_name='API Key')),
                ('status', models.BooleanField(db_column='status', default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Google Place Api',
            },
        ),
    ]
