# Generated by Django 4.1.5 on 2024-04-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_invoiceicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceicon',
            name='active',
        ),
        migrations.RemoveField(
            model_name='invoiceicon',
            name='is_removed',
        ),
    ]
