# Generated by Django 4.1.5 on 2024-04-23 11:08

import core.models
from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_remove_invoiceicon_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFooter',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('stamp', models.FileField(db_column='stamp', unique=True, upload_to=core.models.upload_directory_path, verbose_name='Stamp')),
                ('signature', models.FileField(db_column='signature', unique=True, upload_to=core.models.upload_directory_path, verbose_name='Signature')),
            ],
            options={
                'verbose_name': 'Invoice Footer',
                'verbose_name_plural': 'Invoice Footers',
                'db_table': 'InvoiceFooter',
            },
        ),
    ]
