# Generated by Django 4.1.5 on 2023-05-19 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0016_rename_sector_opportunitytype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0007_resources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='ResourcesContent',
        ),
    ]
