# Generated by Django 4.1.5 on 2023-05-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0016_rename_sector_opportunitytype_and_more'),
        ('superadmin', '0008_rename_resources_resourcescontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcescontent',
            name='attachment',
            field=models.OneToOneField(blank=True, db_column='attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_attachment', to='project_meta.media', verbose_name='Attachment'),
        ),
    ]
