# Generated by Django 4.1.5 on 2024-04-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_invoicefooter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicefooter',
            name='active',
        ),
        migrations.RemoveField(
            model_name='invoicefooter',
            name='is_removed',
        ),
    ]
