# Generated by Django 4.1.5 on 2024-05-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_remove_invoicefooter_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceicon',
            name='link',
            field=models.CharField(blank=True, db_column='link', max_length=250, null=True, verbose_name='Link'),
        ),
    ]
