# Generated by Django 4.1.5 on 2024-05-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tenderdetails_slug'),
        ('superadmin', '0010_invoiceicon_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tender',
            field=models.ForeignKey(blank=True, db_column='tender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tender', to='tenders.tenderdetails', verbose_name='Tender'),
        ),
    ]
