# Generated by Django 4.1.5 on 2023-05-23 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0012_faqcategory_faqquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaqQuestion',
            new_name='FAQ',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelTable(
            name='faq',
            table='FAQ',
        ),
    ]
