# Generated by Django 4.1.5 on 2023-05-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_rename_faqquestion_faq_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.BooleanField(db_column='status', default=True, verbose_name='Status'),
        ),
    ]
