# Generated by Django 4.1.5 on 2023-05-31 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_alter_faq_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcescontent',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, db_column='description', null=True, verbose_name='Description'), default=list, size=None),
            preserve_default=False,
        ),
    ]
