# Generated by Django 4.1.5 on 2023-05-31 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_alter_resourcescontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcescontent',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, db_column='description', null=True, verbose_name='Description'), blank=True, null=True, size=None),
        ),
    ]
