# Generated by Django 4.1.5 on 2023-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0018_categorylogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylogo',
            name='status',
            field=models.BooleanField(blank=True, db_column='status', default=False, null=True, verbose_name='Status'),
        ),
    ]
