# Generated by Django 4.1.5 on 2023-06-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0016_rename_sector_opportunitytype_and_more'),
        ('superadmin', '0019_categorylogo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylogo',
            name='logo',
            field=models.OneToOneField(blank=True, db_column='logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_logo', to='project_meta.media', verbose_name='Logo'),
        ),
    ]
