# Generated by Django 4.1.5 on 2023-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_newsletteruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(db_column='email', default='praveen.vaidhya@digimonk.in', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
