# Generated by Django 4.1.5 on 2023-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0023_alter_newsletteruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
