# Generated by Django 4.1.5 on 2023-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0024_alter_newsletteruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer'), ('vendor', 'Vendor')], db_column='role', default='job_seeker', max_length=250, verbose_name='Role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer'), ('vendor', 'Vendor')], db_column='role', max_length=250, verbose_name='Role'),
        ),
    ]
