# Generated by Django 4.1.5 on 2023-06-14 13:26

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0025_faqcategory_role_alter_faq_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointDetection',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.BigIntegerField(blank=True, db_column='points', default=5, null=True, verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Point Detection',
                'verbose_name_plural': 'Points Detection',
                'db_table': 'PointDetection',
            },
        ),
    ]
