# Generated by Django 4.1.5 on 2023-06-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0026_pointdetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='role',
            field=models.EmailField(blank=True, db_column='role', default='user', max_length=254, null=True, verbose_name='Role'),
        ),
    ]
