# Generated by Django 4.1.5 on 2023-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0027_newsletteruser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcescontent',
            name='subtitle',
            field=models.CharField(blank=True, db_column='subtitle', max_length=255, null=True, verbose_name='Subtitle'),
        ),
    ]
