# Generated by Django 4.1.5 on 2023-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0029_pointinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointinvoice',
            name='is_send',
            field=models.BooleanField(blank=True, db_column='is_send', default=False, null=True, verbose_name='Is Send'),
        ),
    ]
