# Generated by Django 4.1.5 on 2023-07-24 16:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0030_pointinvoice_is_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('benefit', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, db_column='benefit', max_length=450, null=True, verbose_name='Benefit'), blank=True, null=True, size=None)),
                ('price', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=19, null=True, verbose_name='Price')),
                ('number_of_job', models.BigIntegerField(blank=True, db_column='number_of_job', null=True, verbose_name='Number of Job')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'Packages',
                'ordering': ['-created'],
            },
        ),
    ]
