# Generated by Django 4.1.5 on 2023-07-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0031_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='number_of_job',
        ),
        migrations.AddField(
            model_name='packages',
            name='credit',
            field=models.BigIntegerField(blank=True, db_column='credit', null=True, verbose_name='Credit'),
        ),
    ]
