# Generated by Django 4.1.5 on 2023-07-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0032_remove_packages_number_of_job_packages_credit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'ordering': ['created'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
    ]
