# Generated by Django 4.1.5 on 2023-07-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0033_alter_packages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointinvoice',
            name='note',
            field=models.CharField(blank=True, db_column='note', max_length=255, null=True, verbose_name='Note'),
        ),
    ]
