# Generated by Django 4.1.5 on 2023-07-27 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0034_pointinvoice_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointInvoice',
            new_name='RechargeHistory',
        ),
        migrations.AlterModelOptions(
            name='rechargehistory',
            options={'verbose_name': 'Recharge History', 'verbose_name_plural': 'Recharge History'},
        ),
        migrations.AlterModelTable(
            name='rechargehistory',
            table='RechargeHistory',
        ),
    ]
