# Generated by Django 4.1.5 on 2023-07-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0035_rename_pointinvoice_rechargehistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechargehistory',
            name='invoice_id',
        ),
    ]
