# Generated by Django 4.1.5 on 2023-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0037_remove_rechargehistory_is_send_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='points',
            field=models.BigIntegerField(blank=True, db_column='points', default=0, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comment',
            field=models.TextField(blank=True, db_column='comment', null=True, verbose_name='Comment'),
        ),
    ]
