# Generated by Django 4.1.5 on 2023-10-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0040_googleaddsensecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleaddsensecode',
            name='code',
            field=models.TextField(db_column='code', default='', verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googleaddsensecode',
            name='page_title',
            field=models.CharField(db_column='page_title', default='', max_length=255, verbose_name='Page Title'),
            preserve_default=False,
        ),
    ]
