# Generated by Django 4.1.5 on 2023-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0041_alter_googleaddsensecode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleaddsensecode',
            name='code',
            field=models.TextField(blank=True, db_column='code', null=True, verbose_name='Code'),
        ),
    ]
