# Generated by Django 4.1.5 on 2023-11-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0044_alter_aboutus_slug_alter_content_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargehistory',
            name='package',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('gold', 'Gold'), ('silver', 'Silver'), ('copper', 'Copper')], db_column='package', max_length=250, null=True, verbose_name='Package'),
        ),
    ]
