# Generated by Django 4.1.5 on 2024-03-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0047_userrights_usersubrights_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrights',
            name='rights_value',
            field=models.CharField(blank=True, db_column='rights_value', max_length=255, null=True, verbose_name='Rights Value'),
        ),
    ]
