# Generated by Django 4.1.5 on 2024-03-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0048_userrights_rights_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubrights',
            name='subrights_value',
            field=models.CharField(blank=True, db_column='subrights_value', max_length=255, null=True, verbose_name='Subrights Value'),
        ),
    ]
