# Generated by Django 4.1.5 on 2023-01-20 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employer", "0002_blacklist_created_by_blacklist_updated_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="blacklist", name="updated_by",),
        migrations.AddField(
            model_name="blacklist",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified By",
            ),
        ),
    ]
