# Generated by Django 4.1.5 on 2024-03-06 12:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('interview_at', models.DateTimeField(blank=True, db_column='interview_at', null=True, verbose_name='Interview Planned At')),
                ('shortlisted_at', models.DateTimeField(blank=True, db_column='shortlisted_at', null=True, verbose_name='Short Listed At')),
                ('rejected_at', models.DateTimeField(blank=True, db_column='rejected_at', null=True, verbose_name='Rejected At')),
                ('short_letter', models.TextField(blank=True, db_column='short_letter', null=True, verbose_name='Short Letter')),
            ],
            options={
                'verbose_name': 'Applied Job',
                'verbose_name_plural': 'Applied Jobs',
                'db_table': 'AppliedJob',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AppliedJobAttachmentsItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Applied Job Attachment Item',
                'verbose_name_plural': 'Applied Job Attachment Items',
                'db_table': 'AppliedJobAttachmentsItem',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_address', models.CharField(blank=True, db_column='name_or_address', max_length=250, null=True, verbose_name='Name or Address')),
                ('cover_letter', models.TextField(blank=True, db_column='cover_letter', null=True, verbose_name='Cover Letter')),
                ('created', model_utils.fields.AutoCreatedField(db_column='created', default=django.utils.timezone.now, editable=False, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Cover Letter',
                'verbose_name_plural': 'Cover Letters',
                'db_table': 'CoverLetter',
            },
        ),
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True, verbose_name='End Date')),
                ('institute', models.CharField(db_column='institute', max_length=255, verbose_name='Institute')),
            ],
            options={
                'verbose_name': 'Education Record',
                'verbose_name_plural': 'Education Records',
                'db_table': 'EducationRecord',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True, verbose_name='End Date')),
                ('organization', models.CharField(db_column='organization', max_length=255, verbose_name='Organization')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Employment Record',
                'verbose_name_plural': 'Employment Records',
                'db_table': 'EmploymentRecord',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobPreferences',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('is_available', models.BooleanField(blank=True, db_column='is_available', default=False, null=True, verbose_name='Is Available')),
                ('display_in_search', models.BooleanField(blank=True, db_column='display_in_search', default=False, null=True, verbose_name='Display in Search')),
                ('is_part_time', models.BooleanField(blank=True, db_column='is_part_time', default=False, null=True, verbose_name='Is Part Time')),
                ('is_full_time', models.BooleanField(blank=True, db_column='is_full_time', default=False, null=True, verbose_name='Is Full Time')),
                ('has_contract', models.BooleanField(blank=True, db_column='has_contract', default=False, null=True, verbose_name='Has Contract')),
                ('expected_salary', models.DecimalField(blank=True, db_column='expected_salary', decimal_places=2, max_digits=19, null=True, verbose_name='Expected Salary')),
                ('pay_period', models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('hourly', 'Hourly')], db_column='pay_period', default='monthly', max_length=255, null=True, verbose_name='Pay Period')),
            ],
            options={
                'verbose_name': 'Job Preferences',
                'verbose_name_plural': 'Job Preferences',
                'db_table': 'JobPreferences',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerLanguageProficiency',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('written', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='written', max_length=255, verbose_name='Written')),
                ('spoken', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent')], db_column='spoken', max_length=255, verbose_name='Spoken')),
            ],
            options={
                'verbose_name': 'Job Seeker Language Proficiency',
                'verbose_name_plural': 'Job Seeker Language Proficiencies',
                'db_table': 'JobSeekerLanguageProficiency',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerSkill',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Job Seeker Skill',
                'verbose_name_plural': 'Job Seeker Skills',
                'db_table': 'JobSeekerSkill',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'db_table': 'Resume',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('notified', models.BooleanField(blank=True, db_column='notified', default=False, null=True, verbose_name='Notified')),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'db_table': 'SavedJob',
                'ordering': ['-created'],
            },
        ),
    ]
