# Generated by Django 4.1.5 on 2023-02-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0008_appliedjobattachmentsitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appliedjobattachmentsitem",
            options={
                "verbose_name": "Applied Job Attachment Item",
                "verbose_name_plural": "Applied Job Attachment Items",
            },
        ),
        migrations.AlterModelTable(
            name="appliedjobattachmentsitem", table="AppliedJobAttachmentsItem",
        ),
    ]
