# Generated by Django 4.1.5 on 2023-02-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0004_media_title'),
        ('job_seekers', '0010_remove_educationrecord_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationrecord',
            name='description',
        ),
        migrations.AddField(
            model_name='educationrecord',
            name='education_level',
            field=models.OneToOneField(db_column='education_level', default='05cf8e2f-c116-4519-91fa-9067b67d9c50', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_education', to='project_meta.educationlevel', verbose_name='Education Level'),
            preserve_default=False,
        ),
    ]
