# Generated by Django 4.1.5 on 2023-02-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0013_remove_appliedjob_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedjob',
            options={'ordering': ['-created'], 'verbose_name': 'Applied Job', 'verbose_name_plural': 'Applied Jobs'},
        ),
        migrations.AlterModelOptions(
            name='appliedjobattachmentsitem',
            options={'ordering': ['-created'], 'verbose_name': 'Applied Job Attachment Item', 'verbose_name_plural': 'Applied Job Attachment Items'},
        ),
        migrations.AlterModelOptions(
            name='educationrecord',
            options={'ordering': ['-created'], 'verbose_name': 'Education Record', 'verbose_name_plural': 'Education Records'},
        ),
        migrations.AlterModelOptions(
            name='employmentrecord',
            options={'ordering': ['-created'], 'verbose_name': 'Employment Record', 'verbose_name_plural': 'Employment Records'},
        ),
        migrations.AlterModelOptions(
            name='jobseekerlanguageproficiency',
            options={'ordering': ['-created'], 'verbose_name': 'Job Seeker Language Proficiency', 'verbose_name_plural': 'Job Seeker Language Proficiencies'},
        ),
        migrations.AlterModelOptions(
            name='jobseekerskill',
            options={'ordering': ['-created'], 'verbose_name': 'Job Seeker Skill', 'verbose_name_plural': 'Job Seeker Skills'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AlterModelOptions(
            name='savedjob',
            options={'ordering': ['-created'], 'verbose_name': 'Saved Job', 'verbose_name_plural': 'Saved Jobs'},
        ),
    ]
