# Generated by Django 4.1.5 on 2023-03-30 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_seekers', '0015_savedjob_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreferences',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('is_available', models.BooleanField(blank=True, db_column='is_available', default=False, null=True, verbose_name='Is Available')),
                ('is_display', models.BooleanField(blank=True, db_column='is_display', default=False, null=True, verbose_name='Is Display')),
                ('is_part_time', models.BooleanField(blank=True, db_column='is_part_time', default=False, null=True, verbose_name='Is Part Time')),
                ('is_full_time', models.BooleanField(blank=True, db_column='is_full_time', default=False, null=True, verbose_name='Is Full Time')),
                ('has_contract', models.BooleanField(blank=True, db_column='has_contract', default=False, null=True, verbose_name='Has Contract')),
                ('expected_salary', models.DecimalField(blank=True, db_column='expected_salary', decimal_places=2, max_digits=19, null=True, verbose_name='Expected Salary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Preferences',
                'verbose_name_plural': 'Job Preferences',
                'db_table': 'JobPreferences',
                'ordering': ['-created'],
            },
        ),
    ]
