# Generated by Django 4.1.5 on 2023-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0018_alter_jobpreferences_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpreferences',
            name='is_display',
        ),
        migrations.AddField(
            model_name='jobpreferences',
            name='display_in_search',
            field=models.BooleanField(blank=True, db_column='display_in_search', default=False, null=True, verbose_name='Display in Search'),
        ),
    ]
