# Generated by Django 4.1.5 on 2023-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0019_remove_jobpreferences_is_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='interview_at',
            field=models.DateTimeField(blank=True, db_column='interview_at', null=True, verbose_name='Interview Planned At'),
        ),
    ]
