# Generated by Django 4.1.5 on 2024-01-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0024_coverletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='job_title',
        ),
    ]
