# Generated by Django 4.1.5 on 2024-01-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0025_remove_coverletter_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='active',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='is_removed',
        ),
    ]
