# Generated by Django 4.1.5 on 2024-01-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0019_alter_choice_slug_alter_city_slug_alter_country_slug_and_more'),
        ('job_seekers', '0026_remove_resume_active_remove_resume_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_path',
            field=models.OneToOneField(blank=True, db_column='file_path', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_file_path', to='project_meta.media', verbose_name='File Path'),
        ),
    ]
