# Generated by Django 4.1.5 on 2024-01-12 16:46

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0027_alter_resume_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_column='created', default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
    ]
