# Generated by Django 4.1.5 on 2023-01-17 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], db_column='gender', max_length=255, null=True, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, default='dob', null=True, verbose_name='Date of Birth')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('other', 'Other'), ('fresher', 'Fresher')], db_column='employment_status', default='employment_status', max_length=255, verbose_name='Employment Status')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('market_information_notification', models.BooleanField(db_column='market_information_notification', default=True, verbose_name='Market Information Notification')),
                ('job_notification', models.BooleanField(db_column='job_notification', default=True, verbose_name='Job Notification')),
                ('highest_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)sHighestEducations', to='project_meta.educationlevel', verbose_name='Highest Education')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sJobSeeker', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Seeker Profile',
                'verbose_name_plural': 'Job Seeker Profiles',
                'db_table': 'JobSeekerProfile',
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('organization_type', models.CharField(blank=True, choices=[('government', 'Government'), ('ngo', 'NGO'), ('business', 'Business')], db_column='organization_type', max_length=255, null=True, verbose_name='Organization Type')),
                ('market_information_notification', models.BooleanField(db_column='market_information_notification', default=False, verbose_name='Market Information Notification')),
                ('other_notification', models.BooleanField(db_column='other_notification', default=False, verbose_name='Other Notification')),
                ('license_id', models.CharField(blank=True, db_column='license_id', max_length=255, null=True, verbose_name='License Id')),
                ('license_id_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)sLicenseFiles', to='project_meta.media', verbose_name='License File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)sEmployer', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
                'db_table': 'EmployerProfile',
            },
        ),
    ]
