# Generated by Django 4.1.5 on 2024-03-06 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, db_column='address', null=True, verbose_name='Address')),
                ('website', models.URLField(blank=True, db_column='website', null=True, verbose_name='Web Site')),
                ('market_information_notification', models.BooleanField(db_column='market_information_notification', default=False, verbose_name='Market Information Notification')),
                ('other_notification', models.BooleanField(db_column='other_notification', default=False, verbose_name='Other Notification')),
                ('license_id', models.CharField(blank=True, db_column='license_id', max_length=255, null=True, verbose_name='License Id')),
                ('is_verified', models.BooleanField(blank=True, db_column='is_verified', default=False, null=True, verbose_name='Is Verified')),
                ('points', models.BigIntegerField(blank=True, db_column='points', default=500, null=True, verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
                'db_table': 'EmployerProfile',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_column='gender', max_length=255, verbose_name='Gender')),
                ('profile_title', models.CharField(blank=True, db_column='profile_title', max_length=255, null=True, verbose_name='Profile Title')),
                ('dob', models.DateField(blank=True, db_column='dob', null=True, verbose_name='Date of Birth')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('other', 'Other'), ('fresher', 'Fresher')], db_column='employment_status', max_length=255, verbose_name='Employment Status')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('market_information_notification', models.BooleanField(db_column='market_information_notification', default=True, verbose_name='Market Information Notification')),
                ('job_notification', models.BooleanField(db_column='job_notification', default=True, verbose_name='Job Notification')),
                ('experience', models.BigIntegerField(blank=True, db_column='experience', null=True, verbose_name='Experience')),
                ('short_summary', models.TextField(blank=True, db_column='short_summary', null=True, verbose_name='Short Summary')),
                ('home_address', models.TextField(blank=True, db_column='home_address', null=True, verbose_name='Home Address')),
                ('personal_website', models.TextField(blank=True, db_column='personal_website', null=True, verbose_name='Personal Website')),
            ],
            options={
                'verbose_name': 'Job Seeker Profile',
                'verbose_name_plural': 'Job Seeker Profiles',
                'db_table': 'JobSeekerProfile',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, verbose_name='Email Address')),
                ('mobile_number', models.CharField(blank=True, db_column='mobile_number', max_length=13, null=True, verbose_name='Mobile Number')),
                ('country_code', models.CharField(blank=True, db_column='country_code', max_length=250, null=True, validators=[django.core.validators.RegexValidator(message='Invalid country code', regex='^\\+[1-9]\\d{0,2}$')], verbose_name='Country Code')),
                ('name', models.CharField(blank=True, db_column='name', max_length=250, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'db_table': 'Reference',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytic',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='date', null=True, verbose_name='Date')),
                ('count', models.BigIntegerField(blank=True, db_column='count', default=0, null=True, verbose_name='Count')),
            ],
            options={
                'verbose_name': 'User Analytic',
                'verbose_name_plural': 'User Analytics',
                'db_table': 'UserAnalytic',
            },
        ),
        migrations.CreateModel(
            name='UserFilters',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('job_seeker', 'Job Seeker'), ('employer', 'Employer'), ('vendor', 'Vendor')], db_column='role', max_length=250, verbose_name='Role')),
                ('title', models.TextField(db_column='title', verbose_name='Title')),
                ('is_full_time', models.BooleanField(blank=True, db_column='is_full_time', null=True, verbose_name='Is Full-time')),
                ('is_part_time', models.BooleanField(blank=True, db_column='is_part_time', null=True, verbose_name='Is Part-time')),
                ('availability', models.BooleanField(blank=True, db_column='availability', null=True, verbose_name='Availability')),
                ('is_notification', models.BooleanField(blank=True, db_column='is_notification', null=True, verbose_name='Is Notification')),
                ('has_contract', models.BooleanField(blank=True, db_column='has_contract', null=True, verbose_name='Has Contract')),
                ('salary_min', models.CharField(blank=True, db_column='salary_min', max_length=250, null=True, verbose_name='Salary Min')),
                ('salary_max', models.CharField(blank=True, db_column='salary_max', max_length=250, null=True, verbose_name='Salary Max')),
                ('experience', models.BigIntegerField(blank=True, db_column='experience', null=True, verbose_name='Experience')),
                ('years_in_market', models.BigIntegerField(blank=True, db_column='years_in_market', null=True, verbose_name='Years in Market')),
            ],
            options={
                'verbose_name': 'User Filter',
                'verbose_name_plural': 'User Filters',
                'db_table': 'UserFilters',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, db_column='website', null=True, verbose_name='Web Site')),
                ('market_information_notification', models.BooleanField(db_column='market_information_notification', default=False, verbose_name='Market Information Notification')),
                ('other_notification', models.BooleanField(db_column='other_notification', default=False, verbose_name='Other Notification')),
                ('license_id', models.CharField(blank=True, db_column='license_id', max_length=255, null=True, verbose_name='License Id')),
                ('registration_number', models.CharField(blank=True, db_column='registration_number', max_length=255, null=True, verbose_name='Registration Number')),
                ('operating_years', models.BigIntegerField(blank=True, db_column='operating_years', null=True, verbose_name='Operating Years')),
                ('jobs_experience', models.BigIntegerField(blank=True, db_column='jobs_experience', null=True, verbose_name='Jobs Experience')),
                ('address', models.TextField(blank=True, db_column='address', null=True, verbose_name='Address')),
                ('city', models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City')),
                ('country', models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'db_table': 'VendorProfile',
                'ordering': ['created'],
            },
        ),
    ]
