# Generated by Django 4.1.5 on 2023-02-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_meta", "0003_country_educationlevel_language_skill_city"),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        blank=True,
                        db_column="active",
                        default=True,
                        null=True,
                        verbose_name="Active",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("government", "Government"),
                            ("ngo", "NGO"),
                            ("business", "Business"),
                        ],
                        db_column="organization_type",
                        max_length=255,
                        verbose_name="Organization Type",
                    ),
                ),
                (
                    "market_information_notification",
                    models.BooleanField(
                        db_column="market_information_notification",
                        default=False,
                        verbose_name="Market Information Notification",
                    ),
                ),
                (
                    "other_notification",
                    models.BooleanField(
                        db_column="other_notification",
                        default=False,
                        verbose_name="Other Notification",
                    ),
                ),
                (
                    "license_id",
                    models.CharField(
                        blank=True,
                        db_column="license_id",
                        max_length=255,
                        null=True,
                        verbose_name="License Id",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "license_id_file",
                    models.OneToOneField(
                        blank=True,
                        db_column="license_id_file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_license_files",
                        to="project_meta.media",
                        verbose_name="License File",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employer Profile",
                "verbose_name_plural": "Employer Profiles",
                "db_table": "EmployerProfile",
            },
        ),
    ]
