# Generated by Django 4.1.5 on 2023-01-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='dob',
            field=models.DateField(blank=True, db_column='dob', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('other', 'Other'), ('fresher', 'Fresher')], db_column='employment_status', default='employed', max_length=255, verbose_name='Employment Status'),
        ),
    ]
