# Generated by Django 4.1.5 on 2023-02-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_employerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Trans')], db_column='gender', max_length=255, verbose_name='Gender'),
        ),
    ]
