# Generated by Django 4.1.5 on 2023-02-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_employerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerprofile',
            options={'ordering': ['created'], 'verbose_name': 'Employer Profile', 'verbose_name_plural': 'Employer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='jobseekerprofile',
            options={'ordering': ['created'], 'verbose_name': 'Job Seeker Profile', 'verbose_name_plural': 'Job Seeker Profiles'},
        ),
    ]
