# Generated by Django 4.1.5 on 2023-03-31 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0005_alter_city_options_alter_country_options_and_more'),
        ('user_profile', '0003_alter_employerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='city',
            field=models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country'),
        ),
    ]
