# Generated by Django 4.1.5 on 2023-04-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0018_alter_jobpreferences_user'),
        ('project_meta', '0007_remove_jobseekercategory_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0004_jobseekerprofile_city_jobseekerprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilters',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.TextField(db_column='title', verbose_name='Title')),
                ('is_full_time', models.BooleanField(blank=True, db_column='is_full_time', null=True, verbose_name='Is Full-time')),
                ('is_part_time', models.BooleanField(blank=True, db_column='is_part_time', null=True, verbose_name='Is Part-time')),
                ('is_notification', models.BooleanField(blank=True, db_column='is_notification', null=True, verbose_name='Is Notification')),
                ('has_contract', models.BooleanField(blank=True, db_column='has_contract', null=True, verbose_name='Has Contract')),
                ('salary_min', models.TextField(blank=True, db_column='salary_min', null=True, verbose_name='Salary Min')),
                ('salary_max', models.TextField(blank=True, db_column='salary_max', null=True, verbose_name='Salary Max')),
                ('category', models.ManyToManyField(blank=True, db_column='category', null=True, related_name='%(app_label)s_%(class)s_category', to='job_seekers.categories', verbose_name='Category')),
                ('city', models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City')),
                ('country', models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Filter',
                'verbose_name_plural': 'User Filters',
                'db_table': 'UserFilters',
                'ordering': ['-created'],
            },
        ),
    ]
