# Generated by Django 4.1.5 on 2023-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_employerprofile_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='organization_type',
            field=models.CharField(choices=[('government', 'Government'), ('ngo', 'NGO'), ('business', 'Business')], db_column='organization_type', default='business', max_length=255, verbose_name='Organization Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('other', 'Other'), ('fresher', 'Fresher')], db_column='employment_status', max_length=255, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_column='gender', default='male', max_length=255, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
