# Generated by Django 4.1.5 on 2023-01-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_employerprofile_organization_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='organization_name',
            field=models.CharField(db_column='organization_name', default='', max_length=255, verbose_name='Organization Name'),
            preserve_default=False,
        ),
    ]
