# Generated by Django 4.1.5 on 2023-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_userfilters_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilters',
            name='salary_max',
            field=models.CharField(blank=True, db_column='salary_max', max_length=250, null=True, verbose_name='Salary Max'),
        ),
        migrations.AlterField(
            model_name='userfilters',
            name='salary_min',
            field=models.CharField(blank=True, db_column='salary_min', max_length=250, null=True, verbose_name='Salary Min'),
        ),
    ]
