# Generated by Django 4.1.5 on 2023-01-31 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0004_remove_city_created_remove_city_modified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0008_employerprofile_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='organization_name',
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='license_id_file',
            field=models.OneToOneField(blank=True, db_column='license_id_file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_license_files', to='project_meta.media', verbose_name='License File'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
