# Generated by Django 4.1.5 on 2023-05-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_userfilters_sub_category_alter_userfilters_category'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='jobseekerprofile',
        #     name='exprience',
        #     field=models.BigIntegerField(blank=True, db_column='exprience', null=True, verbose_name='Exprience'),
        # ),
    ]
