# Generated by Django 4.1.5 on 2023-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_jobseekerprofile_exprience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='exprience',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.BigIntegerField(blank=True, db_column='experience', null=True, verbose_name='Experience'),
        ),
    ]
