# Generated by Django 4.1.5 on 2023-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_remove_jobseekerprofile_exprience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilters',
            name='experience',
            field=models.BigIntegerField(blank=True, db_column='experience', null=True, verbose_name='Experience'),
        ),
    ]
