# Generated by Django 4.1.5 on 2023-05-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0014_delete_jobseekercategory'),
        ('user_profile', '0013_userfilters_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='address',
            field=models.TextField(blank=True, db_column='address', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='city',
            field=models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True, db_column='website', null=True, verbose_name='Web Site'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='organization_type',
            field=models.CharField(choices=[('government', 'Government'), ('ngo', 'NGO'), ('business', 'Business'), ('private', 'Private'), ('public', 'Public')], db_column='organization_type', max_length=255, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='organization_type',
            field=models.CharField(choices=[('government', 'Government'), ('ngo', 'NGO'), ('business', 'Business'), ('private', 'Private'), ('public', 'Public')], db_column='organization_type', max_length=255, verbose_name='Organization Type'),
        ),
    ]
