# Generated by Django 4.1.5 on 2023-05-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0015_choice'),
        ('user_profile', '0014_employerprofile_address_employerprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='organization_type',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='organization_type',
            field=models.ManyToManyField(db_column='organization_type', related_name='%(app_label)s_%(class)s_organization_types', to='project_meta.choice', verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='organization_type',
            field=models.ManyToManyField(db_column='organization_type', related_name='%(app_label)s_%(class)s_organization_types', to='project_meta.choice', verbose_name='Organization Type'),
        ),
    ]
