# Generated by Django 4.1.5 on 2023-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_alter_jobslanguageproficiency_spoken_and_more'),
        ('user_profile', '0015_remove_employerprofile_organization_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.BigIntegerField(blank=True, db_column='experience', null=True, verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='userfilters',
            name='sub_category',
            field=models.ManyToManyField(blank=True, db_column='sub_category', null=True, related_name='%(app_label)s_%(class)s_sub_category', to='jobs.jobsubcategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='userfilters',
            name='category',
            field=models.ManyToManyField(blank=True, db_column='category', null=True, related_name='%(app_label)s_%(class)s_category', to='jobs.jobcategory', verbose_name='Category'),
        ),
    ]
