# Generated by Django 4.1.5 on 2023-05-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_jobseekerprofile_experience_userfilters_sub_category_and_more'),
        ('user_profile', '0016_vendorprofile_address_vendorprofile_city_and_more'),
    ]

    operations = [
    ]
