# Generated by Django 4.1.5 on 2023-05-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0016_rename_sector_opportunitytype_and_more'),
        ('user_profile', '0016_jobseekerprofile_experience_userfilters_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(blank=True, db_column='address', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='city',
            field=models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='website',
            field=models.URLField(blank=True, db_column='website', null=True, verbose_name='Web Site'),
        ),
    ]
