# Generated by Django 4.1.5 on 2023-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_vendorprofile_address_vendorprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilters',
            name='sub_category',
            field=models.ManyToManyField(blank=True, db_column='sub_category', null=True, related_name='%(app_label)s_%(class)s_sub_category', to='jobs.jobsubcategory', verbose_name='Sub Category'),
        ),
    ]
