# Generated by Django 4.1.5 on 2023-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0016_rename_sector_opportunitytype_and_more'),
        ('user_profile', '0018_userfilters_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilters',
            name='organization_type',
            field=models.ManyToManyField(blank=True, db_column='organization_type', null=True, related_name='%(app_label)s_%(class)s_organization_types', to='project_meta.choice', verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='userfilters',
            name='sector',
            field=models.ManyToManyField(blank=True, db_column='sector', null=True, related_name='%(app_label)s_%(class)s_sector', to='project_meta.choice', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='userfilters',
            name='tag',
            field=models.ManyToManyField(blank=True, db_column='tag', null=True, related_name='%(app_label)s_%(class)s_tag', to='project_meta.tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='userfilters',
            name='years_in_market',
            field=models.BigIntegerField(blank=True, db_column='years_in_market', null=True, verbose_name='Years in Market'),
        ),
    ]
