# Generated by Django 4.1.5 on 2023-06-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_userfilters_organization_type_userfilters_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_verified',
            field=models.BooleanField(blank=True, db_column='is_verified', default=False, null=True, verbose_name='Is Verified'),
        ),
    ]
