# Generated by Django 4.1.5 on 2023-06-14 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0020_employerprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='points',
            field=models.BigIntegerField(blank=True, db_column='points', default=500, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
