# Generated by Django 4.1.5 on 2023-06-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_employerprofile_points_alter_employerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilters',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('job_seeker', 'Job Seeker'), ('employer', 'Employer'), ('vendor', 'Vendor')], db_column='role', default='vendor', max_length=250, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
