# Generated by Django 4.1.5 on 2023-07-04 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0022_userfilters_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytic',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='date', null=True, verbose_name='Date')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Analytic',
                'verbose_name_plural': 'User Analytics',
                'db_table': 'UserAnalytic',
            },
        ),
    ]
