# Generated by Django 4.1.5 on 2023-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0024_useranalytic_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_title',
            field=models.CharField(blank=True, db_column='profile_title', max_length=255, null=True, verbose_name='Profile Title'),
        ),
    ]
