# Generated by Django 4.1.5 on 2024-01-04 16:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0025_jobseekerprofile_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='home_address',
            field=models.TextField(blank=True, db_column='home_address', null=True, verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='job_title',
            field=models.CharField(blank=True, db_column='job_title', max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='personal_website',
            field=models.TextField(blank=True, db_column='personal_website', null=True, verbose_name='Personal Website'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='short_summary',
            field=models.TextField(blank=True, db_column='short_summary', null=True, verbose_name='Short Summary'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, verbose_name='Email Address')),
                ('mobile_number', models.CharField(blank=True, db_column='mobile_number', max_length=13, null=True, verbose_name='Mobile Number')),
                ('country_code', models.CharField(blank=True, db_column='country_code', max_length=250, null=True, validators=[django.core.validators.RegexValidator(message='Invalid country code', regex='^\\+[1-9]\\d{0,2}$')], verbose_name='Country Code')),
                ('name', models.CharField(blank=True, db_column='name', max_length=250, null=True, verbose_name='Name')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'db_table': 'Reference',
            },
        ),
    ]
