# Generated by Django 4.1.5 on 2024-01-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_jobseekerprofile_home_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='job_title',
        ),
    ]
