# Generated by Django 4.1.5 on 2023-05-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_appliedtender_appliedtenderattachmentsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedtender',
            name='active',
        ),
        migrations.RemoveField(
            model_name='appliedtender',
            name='is_removed',
        ),
    ]
