# Generated by Django 4.1.5 on 2023-01-18 10:29

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_meta', '0003_alter_city_active_alter_city_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, db_column='slug', editable=False, null=True, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'JobCategory',
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='Title')),
                ('budget_currency', models.CharField(db_column='budget_currency', default='KES', max_length=5, verbose_name='Budget Currency')),
                ('budget_amount', models.DecimalField(db_column='budget_amount', decimal_places=2, max_digits=19, verbose_name='Budget Amount')),
                ('budget_pay_period', models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('hourly', 'Hourly')], db_column='budget_pay_period', max_length=255, null=True, verbose_name='Budget Pay Period')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('address', models.TextField(db_column='address', verbose_name='Address')),
                ('is_full_time', models.BooleanField(blank=True, db_column='is_full_time', default=False, null=True, verbose_name='Is Full-time')),
                ('is_part_time', models.BooleanField(blank=True, db_column='is_part_time', default=False, null=True, verbose_name='Is Part-time')),
                ('has_contract', models.BooleanField(blank=True, db_column='has_contract', default=False, null=True, verbose_name='Has Contract')),
                ('contact_email', models.EmailField(blank=True, db_column='contact_email', max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, db_column='contact_phone', max_length=15, null=True, verbose_name='Contact Phone')),
                ('contact_whatsapp', models.CharField(blank=True, db_column='contact_whatsapp', max_length=15, null=True, verbose_name='Contact Whatsapp')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_column='status', max_length=25, null=True, verbose_name='Status')),
                ('city', models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_city', to='project_meta.city', verbose_name='City')),
                ('country', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_country', to='project_meta.country', verbose_name='Country')),
                ('highest_education', models.ForeignKey(blank=True, db_column='highest_education', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_highest_education', to='project_meta.educationlevel', verbose_name='Highest Education')),
                ('job_category_1', models.ForeignKey(db_column='job_category_1', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_job_category_1', to='job.jobcategory', verbose_name='Job Category 1')),
                ('job_category_2', models.ForeignKey(blank=True, db_column='job_category_2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_job_category_2', to='job.jobcategory', verbose_name='Job Category 2')),
                ('language_1', models.ForeignKey(db_column='language_1', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_language_1', to='project_meta.language', verbose_name='Language 1')),
                ('language_2', models.ForeignKey(blank=True, db_column='language_2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_language_2', to='project_meta.language', verbose_name='Language 2')),
                ('language_3', models.ForeignKey(blank=True, db_column='language_3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_language_3', to='project_meta.language', verbose_name='Language 3')),
                ('skill_1', models.ForeignKey(db_column='skill_1', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_skill_1', to='project_meta.skill', verbose_name='Skill 1')),
                ('skill_2', models.ForeignKey(blank=True, db_column='skill_2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_skill_2', to='project_meta.skill', verbose_name='Skill 2')),
                ('skill_3', models.ForeignKey(blank=True, db_column='skill_3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_skill_3', to='project_meta.skill', verbose_name='Skill 3')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job Detail',
                'verbose_name_plural': 'Job Details',
                'db_table': 'JobDetails',
            },
        ),
        migrations.CreateModel(
            name='JobAttachmentsItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, db_column='active', default=True, null=True, verbose_name='Active')),
                ('attachment', models.ForeignKey(db_column='attachment', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_attachment', to='project_meta.media', verbose_name='Attachment')),
                ('job', models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_job', to='job.jobdetails', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Job Attachments Item',
                'verbose_name_plural': 'Job Attachments Items',
                'db_table': 'JobAttachmentsItem',
            },
        ),
    ]
