# Generated by Django 4.1.5 on 2023-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_jobattachmentsitem_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='budget_pay_period',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('hourly', 'Hourly')], db_column='budget_pay_period', default='hourly', max_length=255, verbose_name='Budget Pay Period'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hold', 'Hold'), ('deleted', 'Deleted')], db_column='status', default='active', max_length=25, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
