# Generated by Django 4.1.5 on 2023-01-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0004_remove_city_created_remove_city_modified_and_more'),
        ('job', '0004_alter_jobdetails_budget_pay_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='highest_education',
            field=models.ForeignKey(db_column='highest_education', default='', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_highest_education', to='project_meta.educationlevel', verbose_name='Highest Education'),
            preserve_default=False,
        ),
    ]
