# Generated by Django 4.1.5 on 2023-01-31 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_meta', '0004_remove_city_created_remove_city_modified_and_more'),
        ('job', '0005_alter_jobdetails_highest_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobattachmentsitem',
            name='attachment',
            field=models.OneToOneField(db_column='attachment', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_attachment', to='project_meta.media', verbose_name='Attachment'),
        ),
    ]
